settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
- name: another-app
  path: .
  commands:
    run:
      status: true
  watcher:
    paths:
    - /
    - ./../common
    extensions:
    - go
    - html
    - css
    - js
    - yaml
