version: '3'
services:
  tiktok-clean-microservice:
    container_name: "tiktok-clean-microservice"
    build: "./docker/go-develop"
    volumes:
      - ".:${GO_PROJECT_DIR}"
    ports:
      - "8000:8000"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/tiktok-clean-microservice"